export const PROJECT_LIST_REQUEST = 'PROJECT_LIST_REQUEST';
export const PROJECT_LIST_RECEIVED = 'PROJECT_LIST_RECEIVED';
export const PROJECT_LIST_ERROR = 'PROJECT_LIST_ERROR';
export const PROJECT_LIST_SET_PAGE = 'PROJECT_LIST_SET_PAGE';

export const PROJECT_REQUEST = 'PROJECT_REQUEST';
export const PROJECT_RECEIVED = 'PROJECT_RECEIVED';
export const PROJECT_ERROR = 'PROJECT_ERROR';
export const PROJECT_UNLOAD = 'PROJECT_UNLOAD';
export const PROJECT_FORM_UNLOAD = 'PROJECT_FORM_UNLOAD';
export const PROJECT_ADDED = 'PROJECT_ADDED';



export const TASK_LIST_REQUEST = 'TASK_LIST_REQUEST';
export const TASK_LIST_RECEIVED = 'TASK_LIST_RECEIVED';
export const TASK_LIST_ERROR = 'TASK_LIST_ERROR';
export const TASK_LIST_SET_PAGE = 'TASK_LIST_SET_PAGE';
export const TASK_REQUEST = 'TASK_REQUEST';
export const TASK_RECEIVED = 'TASK_RECEIVED';
export const TASK_ERROR = 'TASK_ERROR';
export const TASK_UNLOAD = 'TASK_UNLOAD';
export const TASK_FORM_UNLOAD = 'TASK_FORM_UNLOAD';
export const TASK_ADDED = 'TASK_ADDED';



export const COMMENT_LIST_REQUEST = 'COMMENT_LIST_REQUEST';
export const COMMENT_LIST_RECEIVED = 'COMMENT_LIST_RECEIVED';
export const COMMENT_LIST_ERROR = 'COMMENT_LIST_ERROR';
export const COMMENT_LIST_UNLOAD = 'COMMENT_LIST_UNLOAD';
export const COMMENT_ADDED = 'COMMENT_ADDED';



export const IMAGE_UPLOADED = 'IMAGE_UPLOADED';
export const IMAGE_UPLOAD_REQUEST = 'IMAGE_UPLOAD_REQUEST';
export const IMAGE_UPLOAD_ERROR = 'IMAGE_UPLOAD_ERROR';
export const IMAGE_DELETED = 'IMAGE_DELETED';
export const IMAGE_DELETE_REQUEST = 'IMAGE_DELETE_REQUEST';



export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_SET_ID = 'USER_SET_ID';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_COMPLETE = 'USER_REGISTER_COMPLETE';
export const USER_CONFIRMATION_SUCCESS = 'USER_CONFIRMATION_SUCCESS';

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_RECEIVED = 'USER_PROFILE_RECEIVED';
export const USER_PROFILE_ERROR = 'USER_PROFILE_ERROR';
