export const PROJECT_LIST_REQUEST = 'PROJECT_LIST_REQUEST';
export const PROJECT_LIST_RECEIVED = 'PROJECT_LIST_RECEIVED';
export const PROJECT_LIST_ERROR = 'PROJECT_LIST_ERROR';
export const PROJECT_LIST_SET_PAGE = 'PROJECT_LIST_SET_PAGE';



export const PROJECT_REQUEST = 'PROJECT_REQUEST';
export const PROJECT_RECEIVED = 'PROJECT_RECEIVED';
export const PROJECT_ERROR = 'PROJECT_ERROR';
export const PROJECT_UNLOAD = 'PROJECT_UNLOAD';
export const PROJECT_FORM_UNLOAD = 'PROJECT_FORM_UNLOAD';
export const PROJECT_ADDED = 'PROJECT_ADDED';


export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_SET_ID = 'USER_SET_ID';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_COMPLETE = 'USER_REGISTER_COMPLETE';
export const USER_CONFIRMATION_SUCCESS = 'USER_CONFIRMATION_SUCCESS';



export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_RECEIVED = 'USER_PROFILE_RECEIVED';
export const USER_PROFILE_ERROR = 'USER_PROFILE_ERROR';



export const IMAGE_UPLOADED = 'IMAGE_UPLOADED';
export const IMAGE_UPLOAD_REQUEST = 'IMAGE_UPLOAD_REQUEST';
export const IMAGE_UPLOAD_ERROR = 'IMAGE_UPLOAD_ERROR';
export const IMAGE_DELETED = 'IMAGE_DELETED';
export const IMAGE_DELETE_REQUEST = 'IMAGE_DELETE_REQUEST';

