export const PROJECT_LIST_REQUEST = 'PROJECT_LIST_REQUEST';
export const PROJECT_LIST_RECEIVED = 'PROJECT_LIST_RECEIVED';
export const PROJECT_LIST_ERROR = 'PROJECT_LIST_ERROR';
export const PROJECT_LIST_SET_PAGE = 'PROJECT_LIST_SET_PAGE';

export const PROJECT_REQUEST = 'PROJECT_REQUEST';
export const PROJECT_RECEIVED = 'PROJECT_RECEIVED';
export const PROJECT_ERROR = 'PROJECT_ERROR';
export const PROJECT_UNLOAD = 'PROJECT_UNLOAD';
export const PROJECT_FORM_UNLOAD = 'PROJECT_FORM_UNLOAD';
export const PROJECT_ADDED = 'PROJECT_ADDED';


export const COMMENT_LIST_REQUEST = 'COMMENT_LIST_REQUEST';
export const COMMENT_LIST_RECEIVED = 'COMMENT_LIST_RECEIVED';
export const COMMENT_LIST_ERROR = 'COMMENT_LIST_ERROR';
export const COMMENT_LIST_UNLOAD = 'COMMENT_LIST_UNLOAD';
export const COMMENT_ADDED = 'COMMENT_ADDED';



export const TASK_LIST_REQUEST = 'TASK_LIST_REQUEST';
export const TASK_LIST_RECEIVED = 'TASK_LIST_RECEIVED';
export const TASK_LIST_ERROR = 'TASK_LIST_ERROR';
export const TASK_LIST_UNLOAD = 'TASK_LIST_UNLOAD';
export const TASK_ADDED = 'TASK_ADDED';
export const TASK_UNLOAD = 'TASK_UNLOAD';
export const TASK_REQUEST = 'TASK_REQUEST';
export const TASK_RECEIVED = 'TASK_RECEIVED';
export const TASK_ERROR = 'TASK_ERROR';



export const ALL_TASKS_LIST_SET_PAGE = 'ALL_TASKS_LIST_SET_PAGE';
export const ALL_TASKS_LIST_REQUEST = 'ALL_TASKS_LIST_REQUEST';
export const ALL_TASKS_LIST_RECEIVED = 'ALL_TASKS_LIST_RECEIVED';
export const ALL_TASKS_LIST_ERROR = 'ALL_TASKS_LIST_ERROR';
export const ALL_TASKS_LIST_UNLOAD = 'ALL_TASKS_LIST_UNLOAD';


export const LABEL_LIST_REQUEST = 'LABEL_LIST_REQUEST';
export const LABEL_LIST_RECEIVED = 'LABEL_LIST_RECEIVED';
export const LABEL_LIST_ERROR = 'LABEL_LIST_ERROR';
export const LABEL_LIST_UNLOAD = 'LABEL_LIST_UNLOAD';
export const LABEL_ADDED = 'LABEL_ADDED';


export const MY_TASKS_LIST_REQUEST = 'MY_TASKS_LIST_REQUEST';
export const MY_TASKS_LIST_RECEIVED = 'MY_TASKS_LIST_RECEIVED';
export const MY_TASKS_LIST_ERROR = 'MY_TASKS_LIST_ERROR';



export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_SET_ID = 'USER_SET_ID';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_COMPLETE = 'USER_REGISTER_COMPLETE';
export const USER_CONFIRMATION_SUCCESS = 'USER_CONFIRMATION_SUCCESS';

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_RECEIVED = 'USER_PROFILE_RECEIVED';
export const USER_PROFILE_ERROR = 'USER_PROFILE_ERROR';



export const TEAM_LIST_REQUEST = 'TEAM_LIST_REQUEST';
export const TEAM_LIST_RECEIVED = 'TEAM_LIST_RECEIVED';
export const TEAM_LIST_ERROR = 'TEAM_LIST_ERROR';
export const TEAM_LIST_SET_PAGE = 'TEAM_LIST_SET_PAGE';

export const TEAM_REQUEST = 'TEAM_REQUEST';
export const TEAM_RECEIVED = 'TEAM_RECEIVED';
export const TEAM_ERROR = 'TEAM_ERROR';
export const TEAM_UNLOAD = 'TEAM_UNLOAD';
export const TEAM_FORM_UNLOAD = 'TEAM_FORM_UNLOAD';
export const TEAM_ADDED = 'TEAM_ADDED';
export const TEAM_PATCHED = 'TEAM_PATCHED';


export const MEMBER_LIST_REQUEST = 'MEMBER_LIST_REQUEST';
export const MEMBER_LIST_ERROR = 'MEMBER_LIST_ERROR';
export const MEMBER_LIST_RECEIVED = 'MEMBER_LIST_RECEIVED';
export const MEMBER_PATCHED = 'MEMBER_PATCHED';